config/routes.rb
Rails.application.routes.draw do
  # For Goals
  resources :goals do
    resources :okrs, only: [:new, :create]
    member do
      post 'update_okrs'
    end
  end

  # For OKRs
  resources :okrs, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :okrs, dependent: :destroy

  def calculate_completion_percentage
    total_okrs = okrs.count
    return 0 if total_okrs.zero?

    completed_okrs = okrs.where(completion_status: true).count
    ((completed_okrs.to_f / total_okrs) * 100).round(2)
  end
end

app/models/okr.rb
class Okr < ApplicationRecord
  belongs_to :goal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[ show edit update destroy ]

  # GET /goals or /goals.json
  def index
    @goals = Goal.all.includes(:okrs) # Fetch all goals with associated OKRs

    # Calculate completion status for each goal
    @goals.each do |goal|
      goal.completion_status = calculate_goal_completion_status(goal)
    end
  end

  # GET /goals/1 or /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /goals/:id/update_okrs
  def update_okrs
    @goal = Goal.find(params[:id])

    # Update OKRs based on form data
    okr_params = params.require(:goal).permit(okr_completion_statuses: [])
    okr_params[:okr_completion_statuses].each_with_index do |completion_status, index|
      @goal.okrs[index].update(completion_status: completion_status)
    end

    # Optionally, handle response (e.g., render JSON, redirect)
    respond_to do |format|
      format.html { redirect_to goals_path, notice: 'OKRs updated successfully.' }
      format.json { render json: { message: 'OKRs updated successfully.' } }
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def calculate_goal_completion_status(goal)
    return 0 if goal.okrs.empty? # If there are no OKRs, completion status is 0

    completed_okrs_count = goal.okrs.where(completion_status: true).count
    total_okrs_count = goal.okrs.count

    # Calculate the percentage completion
    completion_percentage = (completed_okrs_count.to_f / total_okrs_count) * 100
    completion_percentage.round(2) # Round to two decimal places
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_goal
    @goal = Goal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def goal_params
    params.require(:goal).permit(:name, :description, :completion_status)
  end
end

app/controllers/okrs_controller.rb
class OkrsController < ApplicationController
  before_action :set_okr, only: %i[ show edit update destroy ]

  # GET /okrs or /okrs.json
  def index
    @okrs = Okr.all
  end

  # GET /okrs/1 or /okrs/1.json
  def show
  end

  # GET /okrs/new
  def new
    @okr = Okr.new
  end

  # GET /okrs/1/edit
  def edit
  end

  # POST /okrs or /okrs.json
  def create
    @okr = Okr.new(okr_params)

    respond_to do |format|
      if @okr.save
        format.html { redirect_to okr_url(@okr), notice: "Okr was successfully created." }
        format.json { render :show, status: :created, location: @okr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @okr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /okrs/1 or /okrs/1.json
  def update
    respond_to do |format|
      if @okr.update(okr_params)
        format.html { redirect_to okr_url(@okr), notice: "Okr was successfully updated." }
        format.json { render :show, status: :ok, location: @okr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @okr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /okrs/1 or /okrs/1.json
  def destroy
    @okr.destroy

    respond_to do |format|
      format.html { redirect_to okrs_url, notice: "Okr was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_okr
      @okr = Okr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def okr_params
      params.require(:okr).permit(:description, :completion_status, :goal_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/okrs_helper.rb
module OkrsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :completion_status %>
    <%= form.number_field :completion_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>All Goals</h1>
<% @goals.each do |goal| %>
  <div>
    <h2><%= goal.name %></h2>
    <p><%= goal.description %></p>
    <p>Completion Status: <%= goal.completion_status %> %</p>

    <%= form_with(model: goal, local: true, html: { class: "update-okrs-form", "data-api-endpoint": update_okrs_goal_path(goal) }) do |form| %>
      <h3>OKRs</h3>
      <ul>
        <% goal.okrs.each do |okr| %>
          <li>
            <%= form.check_box :okr_completion_statuses, { multiple: true }, okr.id, nil %>
            <%= okr.description %>
            <%= form.hidden_field :okr_ids, value: okr.id %> 
          </li>
        <% end %>
      </ul>
      <div class="actions">
        <%= form.submit "Update OKRs" %>
      </div>
    <% end %>
  </div>
<% end %>



<%= javascript_pack_tag 'update_okrs' %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @goal.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Completion status:</strong>
  <%= @goal.completion_status %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/okrs/_form.html.erb
<%= form_with(model: okr, local: true) do |form| %>
  <% if okr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(okr.errors.count, "error") %> prohibited this okr from being saved:</h2>

      <ul>
        <% okr.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :completion_status %>
    <%= form.check_box :completion_status %>
  </div>

  <div class="field">
    <%= form.label :goal_id %>
    <%= form.text_field :goal_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/okrs/edit.html.erb
<h1>Editing Okr</h1>

<%= render 'form', okr: @okr %>

<%= link_to 'Show', @okr %> |
<%= link_to 'Back', okrs_path %>

app/views/okrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Okrs</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Completion status</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @okrs.each do |okr| %>
      <tr>
        <td><%= okr.description %></td>
        <td><%= okr.completion_status %></td>
        <td><%= okr.goal_id %></td>
        <td><%= link_to 'Show', okr %></td>
        <td><%= link_to 'Edit', edit_okr_path(okr) %></td>
        <td><%= link_to 'Destroy', okr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Okr', new_okr_path %>

app/views/okrs/new.html.erb
<h1>New Okr</h1>

<%= render 'form', okr: @okr %>

<%= link_to 'Back', okrs_path %>

app/views/okrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @okr.description %>
</p>

<p>
  <strong>Completion status:</strong>
  <%= @okr.completion_status %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @okr.goal_id %>
</p>

<%= link_to 'Edit', edit_okr_path(@okr) %> |
<%= link_to 'Back', okrs_path %>